INSERT INTO jogadores
(nome, posicao, numero_camisa, flag_ativo)
VALUES
('JOAO SILVA', 'GOLEIRO', 1, 1)
('CARLOS SOUZA', 'LATERAL DIREITO', 2, 1),
('MARCOS LIMA', 'ZAGUEIRO', 3, 1),
('ANDRÉ COSTA', 'ZAGUEIRO', 4, 1),
('PEDRO SANTOS', 'VOLANTE', 5, 1),
('LUCAS ROCHA', 'LATERAL ESQUERDO', 6, 1),
('RAFAEL GOMES', 'MEIA', 7, 1),
('TIAGO OLIVEIRA', 'MEIA', 8, 1),
('VINÍCIUS ALVES', 'ATACANTE', 9, 1),
('FELIPE DUARTE', 'MEIA', 10, 1),
('BRUNO MENDES', 'ATACANTE', 11, 1),
('GUSTAVO TEIXEIRA', 'GOLEIRO', 12, 1),
('EDUARDO BARROS', 'ZAGUEIRO', 13, 1),
('RODRIGO PIRES', 'LATERAL DIREITO', 14, 1),
('MATEUS RIBEIRO', 'VOLANTE', 15, 1),
('HENRIQUE MATOS', 'MEIA', 16, 1),
('DANILO FREITAS', 'MEIA', 17, 1),
('RICARDO LIMA', 'ATACANTE', 18, 1),
('YURI FERNANDES', 'MEIA', 19, 1),
('WESLEY REZENDE', 'ZAGUEIRO', 20, 1),
('ALEX XAVIER', 'ATACANTE', 21, 1),
('KAIO HENRIQUE', 'MEIA', 22, 1),
('JOAQUIM NOGUEIRA', 'GOLEIRO', 23, 1);
